--Veritabaný oluþturma
CREATE DATABASE OVAUN
ON PRIMARY(
NAME='METADATA',
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL13.ERHANDB\MSSQL\DATA\OVAUN.MDF',
SIZE=10 MB,
MAXSIZE=UNLIMITED,
FILEGROWTH=5 MB
)
LOG ON
(
NAME='LOG',
FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL13.ERHANDB\MSSQL\DATA\OVAUN.LDF',
SIZE=2 MB,
MAXSIZE=100 MB,
FILEGROWTH=50 %
)